version: '3.9'
services:
  app:
    image: node:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - arangodb
    volumes:
      - .:/app
 
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: your_root_password
    ports:
      - "8529:8529"
    volumes:
      - arangodata:/var/lib/arangodb3
 
volumes:
  arangodata: