version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - arangodb
    environment:
      - REACT_APP_ARANGODB_URL=http://arangodb:8529 

  arangodb:
    image: arangodb
    ports:
      - "8529:8529" 
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_DB_PASSWORD}
