version: '3.9'

services:
  flask_app:
    build:
      context: ./flask_root
      dockerfile: Dockerfile
    ports:
      - "8432:80"
    environment:
      - DEBUG_USR=admin
      - DEBUG_PWD=restapi
    volumes:
      - flask_app:/app
    networks:
      - general_network


  react_app:
    build:
      context: ./node_root
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - react_app:/app
    networks:
      - general_network

  arangodb:
    image: arangodb:3.11.7
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "BDLaaS"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
      - arangodb_backup:/var/lib/arangodb3-backup
    networks:
      - general_network

volumes:
  flask_app:
  react_app:
  arangodb_data:
  arangodb_apps:
  arangodb_backup:

networks:
  general_network: