version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - arangodb
  arangodb:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: BDLaaS
    ports:
      - "8529:8529"