version: '3.9'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - app_data:/app
    links:
      - arangodb
  arangodb:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: BDLaaS
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_config:/etc/arangodb3

volumes:
  app_data:
  arangodb_data:
  arangodb_config: