{
 "title": "SensorsMonitoration",
 "time": { "from": "2024-03-19T17:45:40.430Z", "to": "2024-03-22T19:03:49.546Z" },
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "label": "Sensor",
    "query": "SELECT DISTINCT entity_id FROM doc.etdevicemeasurement;"
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor Monitoration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS time, CAST(numvalue AS REAL) AS value\r\nFROM doc.etdevicemeasurement\r\nWHERE entity_id LIKE '%$Sensors';"
    }
   ]
  },
  {
   "title": "Actual value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT numvalue\r\nFROM doc.etdevicemeasurement\r\nWHERE entity_id LIKE '%$Sensors' \r\nORDER BY time_index DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Average value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(numvalue) AS average_temperature\r\nFROM doc.etdevicemeasurement\r\nWHERE entity_id LIKE '%$Sensors'; "
    }
   ]
  }
 ]
}